# Generated by Django 5.2.8 on 2025-11-25 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='action',
            field=models.CharField(choices=[('enroll', 'Enroll'), ('drop', 'Drop')], default='enroll', max_length=50),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.subject'),
        ),
    ]
